name: Create Release with Executables

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2025, windows-2022, windows-2019, macos-13, macos-latest, macos-14, macos-15]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build Executable
        run: |
          make executable EXE_NAME=vpi-${{ matrix.os }}

      - name: Upload executables
        uses: actions/upload-artifact@v3
        with:
          name: vpi-${{ matrix.os }}
          path: bin

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: List downloaded artifacts
        run: ls -R artifacts/

      - name: Flatten artifact paths
        run: |
          mkdir -p flattened_artifacts
          find artifacts/ -type f -exec cp {} flattened_artifacts/ \;

      - name: List flattened artifacts
        run: ls -R flattened_artifacts/

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              flattened_artifacts/*
